name: nginx-ingress
version: 0.1.2
appVersion: 1.3.0
description: NGINX Ingress Controller
sources:
  - https://github.com/nginxinc/kubernetes-ingress/tree/master/helm-chart
keywords:
  - ingress
  - nginx
maintainers:
  - name: Damian Curry
    email: damian.curry@nginx.com
  - name: Dean Coakley
    email: dean.coakley@nginx.com

